### ISSUE TITLE
پرسش اینکه نماز خوندیم یا نه

### ISSUE THREAD

**Issue by mimsadAlef** [SCR-IR/gnome-shamsi-calendar#11]
سلام
خیلی خوب می شد اگه نرم افزار از ما می پرسید که نماز خوندیم یا نه و هر یکساعت یه بار بهمون پیام بده
و مثلا یه ربع قبل اینکه قضا بشه هم پیام بده بهمون

**Comment by SCR-IR** [comment]
شاید بهتر باشه در قالب یک افزونه‌ی تخصصی جداگانه چنین امکاناتی فراهم بشه. کاربرد اصلی افزونه‌ی فعلی، «تقویم» هست
