### ISSUE TITLE
ubuntu 21.10

### ISSUE THREAD

**Issue by aliap1376ir** [SCR-IR/gnome-shamsi-calendar#16]
extention installation error while update to last version

**Comment by SCR-IR** [comment]
لطفاً بعد از به‌روزرسانی افزونه، یک‌بار گنوم را ری‌استارت نمایید. درصورتی که همچنان مشکل وجود داشت، اطلاعات زیر را جهت بررسی ارسال بفرمایید:

نسخه گنوم
```gnome-shell --version```

متن خطاها
```sudo journalctl /usr/bin/gnome-shell | grep 'shamsi-calendar@gnome.scr.ir'```

**Comment by SCR-IR** [comment]
همچنین می‌توانید به مکان
~/.local/share/gnome-shell/extensions
مراجعه و پوشه‌ی
shamsi-calendar@gnome.scr.ir
را به‌صورت دستی حذف کنید
سپس مجدداً اقدام به نصب افزونه نمایید
