### ISSUE TITLE
مشکل فونت

### ISSUE THREAD

**Issue by MParvin** [SCR-IR/gnome-shamsi-calendar#17]
مشکل فونت در فدوار ۳۴ گنوم ۴۰.۵ وجود دارد

![Screenshot from 2022-01-22 12-12-03](https://user-images.githubusercontent.com/7812338/150631345-2dd7b1e1-5b68-45c4-91f5-5eaa8960cd65.png)

**Comment by SCR-IR** [comment]
لطفاً از وجود فایل قلم وزیر در مکان زیر، مطمئن شوید

```~/.local/share/fonts/shamsiCalendarFonts/Vazir.ttf```

در حالت طبیعی، با نصب افزونه‌ی تقویم شمسی، این فایل در مسیر بالا کپی خواهد شد؛ مگر اینکه به هر دلیلی در آنجا موجود نباشد که باید افزونه را مجدداً نصب بفرمایید یا فونت را به‌صورت دستی در مکان فوق، قرار دهید

ضمناً توصیه می‌شود نسخه‌ی فدورای خود را نیز ارتقاء دهید
