### ISSUE TITLE
تاریخ در نوار بالا

### ISSUE THREAD

**Issue by ali-hejazi** [SCR-IR/gnome-shamsi-calendar#18]
سلام
بدون ریستارت سیستم عامل تاریخ روی نوار بالا تغییر نمی کند

**Comment by SCR-IR** [comment]
سلام
معمولاً به‌روزرسانی تاریخ، با چند ثانیه تأخیر انجام می‌شود. اگر در سیستم شما بعد از گذشت حداکثر ۵۹ ثانیه همچنان تاریخ عوض نشد، لطفاً نسخه لینوکس و گنوم خود را اعلام بفرمایید تا آزمایش کنیم

```uname -v```
```gnome-shell --version```
