### ISSUE TITLE
Error when adding extension to gnome 3.36.1

### ISSUE THREAD

**Issue by separable** [SCR-IR/gnome-shamsi-calendar#2]
Dec 03 16:43:19 andromeda gnome-shell[1281]: JS ERROR: Extension shamsi-calendar@gnome.scr.ir: Error: Requiring GstAudio, version none: Typelib file for namespace 'GstAudio' (any version) not found
                                             @[home-directory].local/share/gnome-shell/extensions/shamsi-calendar@gnome.scr.ir/sound.js:4:18
                                             @[home-directory].local/share/gnome-shell/extensions/shamsi-calendar@gnome.scr.ir/calendar.js:14:16
                                             @[home-directory].local/share/gnome-shell/extensions/shamsi-calendar@gnome.scr.ir/extension.js:21:18
Dec 03 16:52:06 andromeda gnome-shell[1339]: JS ERROR: Extension shamsi-calendar@gnome.scr.ir: Error: Requiring GstAudio, version none: Typelib file for namespace 'GstAudio' (any version) not found
                                             @[home-directory].local/share/gnome-shell/extensions/shamsi-calendar@gnome.scr.ir/sound.js:4:18
                                             @[home-directory].local/share/gnome-shell/extensions/shamsi-calendar@gnome.scr.ir/calendar.js:14:16
                                             @[home-directory].local/share/gnome-shell/extensions/shamsi-calendar@gnome.scr.ir/extension.js:21:18
Dec 03 21:11:09 andromeda gnome-shell[1305]: JS ERROR: Extension shamsi-calendar@gnome.scr.ir: Error: Requiring GstAudio, version none: Typelib file for namespace 'GstAudio' (any version) not found
                                             @[home-directory].local/share/gnome-shell/extensions/shamsi-calendar@gnome.scr.ir/sound.js:4:18
                                             @[home-directory].local/share/gnome-shell/extensions/shamsi-calendar@gnome.scr.ir/calendar.js:14:16
                                             @[home-directory].local/share/gnome-shell/extensions/shamsi-calendar@gnome.scr.ir/extension.js:21:18
Dec 04 08:20:55 andromeda gnome-shell[1329]: JS ERROR: Extension shamsi-calendar@gnome.scr.ir: Error: Requiring GstAudio, version none: Typelib file for namespace 'GstAudio' (any version) not found
                                             @[home-directory].local/share/gnome-shell/extensions/shamsi-calendar@gnome.scr.ir/sound.js:4:18
                                             @[home-directory].local/share/gnome-shell/extensions/shamsi-calendar@gnome.scr.ir/calendar.js:14:16
                                             @[home-directory].local/share/gnome-shell/extensions/shamsi-calendar@gnome.scr.ir/extension.js:21:18
Dec 04 09:17:46 andromeda gnome-shell[1329]: JS ERROR: Extension shamsi-calendar@gnome.scr.ir: Error: Requiring GstAudio, version none: Typelib file for namespace 'GstAudio' (any version) not found
                                             @[home-directory].local/share/gnome-shell/extensions/shamsi-calendar@gnome.scr.ir/sound.js:4:18
                                             @[home-directory].local/share/gnome-shell/extensions/shamsi-calendar@gnome.scr.ir/calendar.js:14:16
                                             @[home-directory].local/share/gnome-shell/extensions/shamsi-calendar@gnome.scr.ir/extension.js:21:18
Dec 04 09:31:50 andromeda gnome-shell[1305]: JS ERROR: Extension shamsi-calendar@gnome.scr.ir: Error: Requiring GstAudio, version none: Typelib file for namespace 'GstAudio' (any version) not found
                                             @[home-directory].local/share/gnome-shell/extensions/shamsi-calendar@gnome.scr.ir/sound.js:4:18
                                             @[home-directory].local/share/gnome-shell/extensions/shamsi-calendar@gnome.scr.ir/calendar.js:14:16
                                             @[home-directory].local/share/gnome-shell/extensions/shamsi-calendar@gnome.scr.ir/extension.js:21:18
Dec 04 09:33:17 andromeda gnome-shell[1305]: JS ERROR: Extension shamsi-calendar@gnome.scr.ir: Error: Requiring GstAudio, version none: Typelib file for namespace 'GstAudio' (any version) not found
                                             @[home-directory].local/share/gnome-shell/extensions/shamsi-calendar@gnome.scr.ir/sound.js:4:18
                                             @[home-directory].local/share/gnome-shell/extensions/shamsi-calendar@gnome.scr.ir/calendar.js:14:16
                                             @[home-directory].local/share/gnome-shell/extensions/shamsi-calendar@gnome.scr.ir/extension.js:21:18
Dec 04 09:46:46 andromeda gnome-shell[7140]: JS ERROR: Extension shamsi-calendar@gnome.scr.ir: Error: Requiring GstAudio, version none: Typelib file for namespace 'GstAudio' (any version) not found
                                             @[home-directory].local/share/gnome-shell/extensions/shamsi-calendar@gnome.scr.ir/sound.js:4:18
                                             @[home-directory].local/share/gnome-shell/extensions/shamsi-calendar@gnome.scr.ir/calendar.js:14:16
                                             @[home-directory].local/share/gnome-shell/extensions/shamsi-calendar@gnome.scr.ir/extension.js:21:18

**Comment by SCR-IR** [comment]
GstAudio
```Error: Requiring GstAudio, version none: Typelib file for namespace 'GstAudio' (any version) not found```
<div dir=rtl>
معمولاً کتابخانه‌ی مربوط به این خطا به‌همراه گنوم ۳.۲۸ و بالاتر به‌صورت پیشفرض یافت می‌شود.
اینکه نسخه‌ی گنوم شما ۳.۳۶ است و این مشکل را دارید، قدری عجیب است.
<br><br>
لطفاً با پاسخ به چند پرسش، ما را در یافتن دلیل این مشکل یاری فرمایید:
<br>
۱- نام توزیع لینوکس شما و نسخه‌ی آن چیست؟
<br>
۲- آیا میز‌کار اصلی آن از ابتدا گنوم بوده یا اینکه بعداً گنوم را به آن اضافه (نصب) کرده‌اید؟
<br>
۳- آیا این احتمال وجود دارد که کتابخانه‌ی مربوطه را خودتان قبلاً حذف نموده‌باشید؟
<br><br>
البته با نصب بسته‌ی
gir1.2-gst-plugins-base-1.0
احتمالاً مشکل شما حل خواهد شد
</div>

```sudo apt install gir1.2-gst-plugins-base-1.0```
