### ISSUE TITLE
Program preparation for GNOME 42 and gtk4

### ISSUE THREAD

**Issue by mobin-2008** [SCR-IR/gnome-shamsi-calendar#20]
Hello.
Work on Gnome 42 is currently underway.
The most important change in this version is the mandatory use of libadwaita.
Stable versions of gtk4 and libadwaita have been released.
It is better to start working on them now

With respect

- [ ] Porting gui to gtk4 & libadwaita

**Comment by SCR-IR** [comment]
سلام
پیگیر این قضیه هستیم تا اردیبشت‌ماه که انتشار رسمی فدورا و اوبونتو انجام شود و آزمایش‌های قطعی را با نسخه‌های رسمی کامل کنیم.

تجربه‌های قبلی نشان داد که آزمایش با نسخه‌های بتای توزیع‌ها، قطعی نیست.
حتی
GnomeOS

**Comment by mobin-2008** [comment]
گنوم ۴۲ برای آرتیکس لینوکس (آرچ بدون systemd) منتشر شد.
جالبه گنوم افزونه شمارو ناسازگار علامت نمیزنه!
همچنین عملکرد های اصلی افزونه هم به درستی کار می‌کنند!
ولی تنظیمات و بقیه بخش های افزونه با خطا روبرو می‌شوند.

https://user-images.githubusercontent.com/85447245/162612481-3932d2a4-e00e-4465-9ed9-7781360ba787.mp4

**Comment by SCR-IR** [comment]
احتمالاً با به‌روزرسانی اخیر افزونه، باید این مشکل برطرف شود.

**Comment by mobin-2008** [comment]
Fixed on [19.x](https://github.com/SCR-IR/gnome-shamsi-calendar/commit/71a3666d8d37b63c7ee26437f4b6f860213d16a3)
