### ISSUE TITLE
بزرگ بودن پنجره تقویم

### ISSUE THREAD

**Issue by RZHSSNZDH** [SCR-IR/gnome-shamsi-calendar#24]
وقتی روی تقویم در نوار بالا کلیک میکنم و تقویم باز میشه، تقریبا کل صفحه رو میگیره و حتی بخشی‌ش بیرون میره. تا گنوم ۴۱ این مشکل رو نداشتم ولی توی گنوم ۴۲ اینطوری شده. از نگارش ۱۹ افزونه استفاده میکنم.
![نماگرفت از 2022-04-23 19-42-06](https://user-images.githubusercontent.com/69734726/164912234-55306172-2374-417e-8de9-4a09ea12ca8a.png)
خروجی `sudo journalctl /usr/bin/gnome-shell | grep 'shamsi-calendar@gnome.scr.ir'`:
https://paste.ubuntu.ir/nzpjk

**Comment by SCR-IR** [comment]
احتمالاً وضوح تصویر شما کمتر از 768*1024 تنظیم شده یا مقیاس بیشتر از 100 هست. البته به‌دلیل منسوخ‌شدن نمایشگرهای با وضوح پایین، گنوم (و اوبونتو) نیز تغییر رویه می‌دهند و تنظیمات پیشفرض را عوض می‌کنند تا برای نمایشگرهای جدید امروزی، سازگارتر باشند. به‌هرحال، این موضوع به ارتقاء سیستم‌عامل و گنوم شما مربوط می‌شود و هیچ تفاوت خاصی از این بابت بین نسخه‌های ۱۸ و ۱۹ افزونه نداشته‌ایم.

![](https://user-images.githubusercontent.com/43960795/164938662-c1396d1c-dd85-4f9b-82be-16829cc087e9.png)

**Comment by RZHSSNZDH** [comment]
@SCR-IR از این نظر مشکلی نیست و نتظیمات درسته. اندازه همه چیز درسته فقط این اینطوریه

**Comment by SCR-IR** [comment]
یکی از امکاناتی که از قبل برای پیاده‌سازی در آینده برنامه‌ریزی شده، همین امکان تغییر اندازه (و مقیاس) در افزونه هست که إن‌شاءالله فرصت اجرای آن نصیبمان شود.
وضوح نمایشگر شما هست؟
