### ISSUE TITLE
باز نشدن صفحه‌ی تنظیمات

### ISSUE THREAD

**Issue by sjavadez** [SCR-IR/gnome-shamsi-calendar#25]
با سلام
صفحه‌ی تنظیمات اکستنشن روی ابونتو ورژن ۲۲ و گنوم ورژن 42 بالا نمیاد.

**Comment by sjavadez** [comment]
![image](https://user-images.githubusercontent.com/27066228/166627209-493e7d8e-bdc2-457b-8659-7e8307b31e51.png)
![image](https://user-images.githubusercontent.com/27066228/166627247-4f5683c0-9a7f-450a-889a-5abd7b1329f9.png)
توی هیچکدوم از این صفحات باز نشد

**Comment by SCR-IR** [comment]
سلام
آخرین نسخه‌ی افزونه با گنوم ۴۲ و اوبونتو ۲۲.۰۴ کاملاً آزمایش شده و مشکلی ندارد.

اما مشابه مشکل شما قبلاً گاهی برای کاربرانی که اوبونتوی خود را ارتقاء داده‌بودند، مشاهده میشد و راه‌حل آن این بود که ابتدا افزونه را حذف کنید. سپس به پوشه‌ی افزونه‌ها بروید:
```/home/user1/.local/share/gnome-shell/extensions```
و در آنجا اگر پوشه‌ای به‌نام:
```shamsi-calendar@gnome.scr.ir```
یافتید، آن را به‌صورت دستی حذف کنید
و سپس دوباره افزونه را نصب نموده و نتیجه را گزارش بفرمایید
