### ISSUE TITLE
عوض شدن تعطیلات قمری

### ISSUE THREAD

**Issue by Saeidm660** [SCR-IR/gnome-shamsi-calendar#26]
سلام.
امسال ماه رمضان ۳۰ روزه شد ولی تقویم شما آپدیت نشده است.
باید همه تعطیلات قمری یک روز برن جلو.

**Comment by SCR-IR** [comment]
سلام
این اصلاح در همان شب قبل عید فطر انجام شد. باید افزونه را به نسخه ۲۰ ارتقاء دهید
