### ISSUE TITLE
Date template

### ISSUE THREAD

**Issue by sina-rostami** [SCR-IR/gnome-shamsi-calendar#27]
Previously there was an option to set the date template which showing at the top. but in the newer release it is not available and user must choose between some templates.
 
![image](https://user-images.githubusercontent.com/61062593/171987322-b9667471-3444-40ce-8ce8-3ce0fd1caecc.png)

It would be great to make this select bar scrollable :)

Also may you please add this template too? (۱۴۰۱/۳/۱۴)

**Comment by SCR-IR** [comment]
این مشکل در گنوم ۴۲ به‌وجود آمده. فعلاً می‌توانید با فشردن دکمه‌های ↑ و ↓ روی صفحه‌کلید، به گزینه‌های پایین‌تر نیز پیمایش کنید. لازم است ساختار این منوها تغییر کند تا در گنوم ۴۲ قابل پیمایش (اسکرول) شوند.

**Comment by SCR-IR** [comment]
خوشبختانه در گنوم ۴۳ دوباره نوار پیمایش (اسکرول) با این منوها برگشته
