### ISSUE TITLE
عدد ۷ مشکل دارد

### ISSUE THREAD

**Issue by mgholam** [SCR-IR/gnome-shamsi-calendar#28]
on fedora 36

![image](https://user-images.githubusercontent.com/460565/176335264-ba4d3281-45b5-414d-9258-52eb65209c9b.png)

**Comment by mimsadAlef** [comment]
سلام
این فونت رو نصب کنید احتمالا درست بشود
[دانلود](https://github.com/SCR-IR/gnome-shamsi-calendar/blob/main/shamsi-calendar@gnome.scr.ir/fonts/Vazir.ttf?raw=true)
اگه برطرف نشد یکبار افزونه رو پاک کنید و دوباره نصب کنید
در غیر این صورت منتظر جواب تیم scr.ir بمونید

**Comment by yasandev** [comment]
منم همین مشکل رو داشتم و با نصب فونت وزیرمتن حل شد.
