### ISSUE TITLE
اذان عصر و عشاء

### ISSUE THREAD

**Issue by RZHSSNZDH** [SCR-IR/gnome-shamsi-calendar#29]
سلام
خوب میشه اگر گزینه‌ای برای فعال کردن اذان عصر و عشاء وجود داشته باشه. هم برای اذانگو و هم نمایش اوقات شرعی

**Comment by SCR-IR** [comment]
<div dir=rtl>
سلام - این قابلیت وجود دارد و فقط کافیست در بخش تنظیمات افزونه، آن‌ها را فعّال نمایید.
<br/>
از بخش تنظیمات : اوقات شرعی : تنظیمات پیشرفته
</div>

**Comment by RZHSSNZDH** [comment]
فقط یه مشکلی که هست اینه که اذان عصر و عشاء عبارت «اذان» رو پیش از خودشون ندارن:
![نماگرفت از 2022-09-12 10-36-07](https://user-images.githubusercontent.com/69734726/189691160-38e3fae6-ad96-43bf-bed0-9c0511172b5b.png)

**Comment by SCR-IR** [comment]
این موارد، همان عبارت‌های «آغاز وقت فضیلت نماز عصر» و «آغاز وقت فضیلت نماز عشاء» بوده که به‌خاطر کمبود فضا، به‌صورت خلاصه نوشته‌ایم.

موارد اصلی صبح، ظهر و مغرب، علاوه بر اینکه «آغاز وقت فضیلت...» هستند، «آغاز وقت اختصاصی...» و همچنین «آغاز وقت کلی...» نیز می‌باشند. یعنی به‌طور همزمان، ۳ رخداد را اعلام می‌کنند. پس آنها را اذان‌های اصلی می‌دانیم.
اما موارد عصر و عشاء، فقط ۱ رخداد را اعلام می‌کنند(آغاز وقت فضیلت).
لذا برای تفکیک آسان‌تر در ذهن مردم عادی، فقط اذان‌های اصلی را به این صورت نوشتیم تا پیچیدگی آن کمتر شود.
