### ISSUE TITLE
Fade Colors

### ISSUE THREAD

**Issue by sina-rostami** [SCR-IR/gnome-shamsi-calendar#3]
سلام،‌ برای اوقات شرعی رنگ مورد استفاده خواندن متن رو سخت کرده.
![Screenshot from 2020-12-04 16-43-56](https://user-images.githubusercontent.com/61062593/101167984-fe32f200-364f-11eb-940b-bfd8628dd5fb.png)

**Comment by SCR-IR** [comment]
<div dir=rtl>
سلام، درواقع هیچ رنگی نداشته و با قالب گنوم شما تنظیم شده.
<br>
الآن در شاخه‌ی develop اصلاح شد و در نسخه‌ی بعدی هم منتشر می‌شود.
<br>
ممنون که گزارش دادید. اگر هرجای دیگر هم رنگ ناسازگار مشاهده فرمودید، حتماً اعلام کنید.
</div>
