### ISSUE TITLE
Error on upgrade

### ISSUE THREAD

**Issue by badde-media** [SCR-IR/gnome-shamsi-calendar#30]
When trying to upgrade, the installation resulted with ERROR. I deinstalled and tried to reinstall it, resulting in the same ERROR, which unfortunately wasn't further specified.

**Comment by SCR-IR** [comment]
لطفاً بعد از به‌روزرسانی افزونه، یک‌بار گنوم را ری‌استارت نمایید. درصورتی که همچنان مشکل وجود داشت، اطلاعات زیر را جهت بررسی ارسال بفرمایید:

نسخه گنوم
```gnome-shell --version```

متن خطاها
```sudo journalctl /usr/bin/gnome-shell | grep 'shamsi-calendar@gnome.scr.ir'```
