### ISSUE TITLE
Gnome 43 support

### ISSUE THREAD

**Issue by alipirpiran** [SCR-IR/gnome-shamsi-calendar#31]
please add support for the new version of Gnome-Shell. 
Ubuntu 22.10 - Gnome-Shell v43

**Comment by mmehdizadeh** [comment]
Still waiting for update ...

**Comment by SCR-IR** [comment]
انجام شد.
فقط کافیست نسخه‌ی جدید گنوم را در فایل:
metadata.json
اضافه کنید.
سپس درصورت مواجه‌شدن با مشکل یا خطا، خودتان نسبت به رفع آن اقدام کنید یا اینکه گزارش بفرمایید
