### ISSUE TITLE
اشکال در رابط کاربری تنظیمات پیشرفتهٔ اوقات شرعی

### ISSUE THREAD

**Issue by mimsadAlef** [SCR-IR/gnome-shamsi-calendar#34]
![image](https://user-images.githubusercontent.com/70805659/219871756-be585575-70d5-4d39-95ad-06b8ad489007.png)

**Comment by mimsadAlef** [comment]
گنوم 40

**Comment by mimsadAlef** [comment]
![نماگرفت از 2023-03-26 17-05-35](https://user-images.githubusercontent.com/70805659/227779509-5fbcc138-0244-4381-a5cf-6ee523de1f12.png)

در گنوم ۴۳ و GTK4 مشکل هنوز با پرجا هست
(تایتل‌های اذان و غروب و... کنار کادر خودش نیست)

**Comment by SCR-IR** [comment]
<div dir=rtl>
این ویرایش را آزمایش بفرمایید:
[https://github.com/SCR-IR/gnome-shamsi-calendar/archive/refs/heads/develop.zip](https://github.com/SCR-IR/gnome-shamsi-calendar/archive/refs/heads/develop.zip)
</div>

**Comment by SCR-IR** [comment]
این افزونه هنوز طبق GTK3 هست. ان‌شاءالله باید فرصتی پیش بیاید تا بتوانیم کل افزونه را بر اساس GTK4 به‌طور اصولی بازنویسی کنیم. شاید بعد از پوست‌اندازی و مهاجرت توزیع پایه دبیان به گنوم جدید که موجب تغییر اکثر توزیع‌های تابع آن هم می‌شود

**Comment by mimsadAlef** [comment]
![image](https://user-images.githubusercontent.com/70805659/228968344-ca465721-b26a-4c00-b959-76859870be3d.png)
اینم نسخه جدید
ایده خوبی برای رفعش نبوده
باید کنار هر باکس متنش تعریف بشه
