### ISSUE TITLE
کادر اضافی

### ISSUE THREAD

**Issue by RZHSSNZDH** [SCR-IR/gnome-shamsi-calendar#35]
سلام
در صفحه افزونه، یه کادر اضافی هم در کنار وجود داره که ظاهرش رو زشت میکنه (بخش کمرنگ):
![نماگرفت از 2023-07-03 13-22-34](https://github.com/SCR-IR/gnome-shamsi-calendar/assets/69734726/493b7494-13c0-47bd-a171-91f7e702b0c2)
سیستم‌عامل: Debian GNU/Linux trixie/sid
نگارش گنوم: 43.6
سامانه پنجره: وی‌لند

**Comment by SCR-IR** [comment]
سلام
این به قالب گنوم مربوط هست و سعی می‌کنیم قدری اصلاحش کنیم.
البته به‌دلیل فارسی‌کردن محیط گنوم، برای شما یکطرفه شده. متأسفانه در عمل فارسی‌سازی نرم‌افزارها، هنوز آن عادت غلط قدیمی از بین نرفته و همه‌چیز را تغییر جهت می‌دهند و وارونه می‌کنند؛ سپس می‌گویند فارسی کردیم :(

**Comment by RZHSSNZDH** [comment]
در https://extensions.gnome.org/extension/5814/persian-calendar این مشکل وجود نداره فکر کنم (قبلا که وجود نداشت). ببینید اون چیکار کرده.
