### ISSUE TITLE
نام استان ها قابل انتخاب نیست

### ISSUE THREAD

**Issue by Coderx7** [SCR-IR/gnome-shamsi-calendar#37]
سلام 
بعد از نصب افزونه متوجه شدم در خش اوقات شرعی اسکرول موس کار نمیکنه و نمیشه لیست تمامی استان ها و شهر ها رو مشاهده و انتخاب کرد.
مشکل از کجاست؟

**Comment by SCR-IR** [comment]
سلام
اگر گنوم شما جدید (۴۳ یا ۴۴) هست، نسخه آینده افزونه را آزمایش کنید:
https://github.com/SCR-IR/gnome-shamsi-calendar/tree/develop

**Comment by Coderx7** [comment]
> سلام اگر گنوم شما جدید (۴۳ یا ۴۴) هست، نسخه آینده افزونه را آزمایش کنید: https://github.com/SCR-IR/gnome-shamsi-calendar/tree/develop

سلام
نه گنوم ۴۲.۵ هست اوبونتو ۲۲.۰۴.۲ و نسخه اخیرهم تفاوتی نکرد.
چیزی که من دیدم کار می‌کنه اینه که mouse over روی کمبوباکسا کار می‌کنه. یعنی شما موس رو روی این کومبوباکسها هاور کنید و بعد با دکمه اسکرول موس میتونید تغییر بدید به غیر از اون ممکن نیست.
نکته دوم اینکه برای بار اول گویا باید بازنشانی رو زد پنجره رو بست دوباره پنجره رو باز کرد تا کمبوباکسها مقادیر اولیه بگیرن و بشه بصورتی که عرض کردم انتخاب صورت داد که البته عجیبه.

**Comment by SCR-IR** [comment]
درمورد اختفای نوار پیمایش، ایراد از گنوم ۴۲ هست. در گنوم ۴۳ به بالا این ایراد را برطرف کرده‌اند.
اما مشکل دوم در شاخه develop حل شده، قبل از انتشار نسخه رسمی

**Comment by Coderx7** [comment]
سلام 
من باب اطلاع رسانی نصب نسخه develop مشکل دوم رو حل نکرده.
