### ISSUE TITLE
مشکل گنوم ۴۶ ابونتو ۲۴.۰۴

### ISSUE THREAD

**Issue by mtashackori** [SCR-IR/gnome-shamsi-calendar#39]
در گنوم ۴۶ روی اوبونتو ۲۴.۰۴ مشکل هست:
![image](https://github.com/SCR-IR/gnome-shamsi-calendar/assets/16570244/6a01a288-8536-4414-8c6b-f2dca2ced5aa)

**Comment by SCR-IR** [comment]
شاید پس از **به‌روزرسانی** سیستم‌عامل، چنین مشکلی ایجاد شده باشد.
برای ما امکان نصب تمامی توزیع‌ها فراهم نیست؛ لذا اکثراً با نسخه‌های زنده (Live) آزمایش می‌کنیم و هیچ مشکلی با گنوم ۴۶ مشاهده نمی‌شود.
ای کاش دوستانی که توانایی دارند، در رفع اینگونه مشکلات پروژه **همکاری** می‌کردند. متأسفانه داشتن همزمان چندین توزیع نصب‌شده لینوکس، صرفاً جهت امتحان کردن یک افزونه، میسر نیست
