### ISSUE TITLE
عدم اجرا بر روی گنوم ۴۶ ابونتو ۲۴

### ISSUE THREAD

**Issue by persian85** [SCR-IR/gnome-shamsi-calendar#42]
sudo journalctl /usr/bin/gnome-shell | grep 'shamsi-calendar@gnome.scr.ir'
Aug 31 13:08:41 UbuntuDesk gnome-shell[18440]: Extension shamsi-calendar@gnome.scr.ir: Error: Requiring GstAudio, version none: Typelib file for namespace 'GstAudio' (any version) not found
Aug 31 13:09:26 UbuntuDesk gnome-shell[21610]: Extension shamsi-calendar@gnome.scr.ir: Error: Requiring GstAudio, version none: Typelib file for namespace 'GstAudio' (any version) not found

**Comment by jalilimmd** [comment]
من هم همین مشکل رو دارم روی گنوم ۴۶ ابونتو ۲۴
![image](https://github.com/user-attachments/assets/80b4c92b-9b13-4879-b305-141dcf24aecf)

**Comment by SCR-IR** [comment]
لطفاً نسخه جدید را آزمایش بفرمایید:
https://github.com/SCR-IR/gnome-shamsi-calendar/releases
