### ISSUE TITLE
Support Gnome 46.4

### ISSUE THREAD

**Issue by AmirHosseinKarimi** [SCR-IR/gnome-shamsi-calendar#43]
درود.
با توجه به استفاده از نسخه‌ی 46.4 Gnome در سیستم عامل‌هایی مثل مانجارو، افزونه به دلیل عدم پشتیبانی از این نسخه از کار افتاده.

**Comment by SCR-IR** [comment]
سلام. این نسخه جدید را آزمایش کنید:
https://github.com/SCR-IR/gnome-shamsi-calendar/releases
