### ISSUE TITLE
Support for gnome 47

### ISSUE THREAD

**Issue by thantez** [SCR-IR/gnome-shamsi-calendar#44]
Hi. This version of extension seems is unready for gnome 47. Can you make it compatible?
BTW, the command `sudo journalctl /usr/bin/gnome-shell | grep 'shamsi-calendar@gnome.scr.ir'` returns nothing.

**Comment by SCR-IR** [comment]
سلام
انجام شد:
https://github.com/SCR-IR/gnome-shamsi-calendar/releases
