### ISSUE TITLE
مشکل اوقات شرعی بیرون از ایران

### ISSUE THREAD

**Issue by khodayard** [SCR-IR/gnome-shamsi-calendar#5]
لیست شهرها محدود به ایران است و وقتی با طول عرض و جغرافیایی کار می‌کنید هم اوقات شرعی برای شهرهای بیرون از ایران درست کار نمی‌کند.

**Comment by SCR-IR** [comment]
<div dir=rtl>
لیست شهرها صرفاً جهت آسان‌تر‌شدن کار می‌باشد و اجباری برای استفاده از آن نیست.
<br>
شما می‌توانید فقط با وارد‌کردن طول+عرض جغرافیایی (با حدّ‌اقل دو‌رقم اعشار) و نوشتن نام نمایشی مکان (دلخواه)، از برنامه استفاده نمایید.
<br><br>
امّا ناهماهنگی‌ها در خروجی برنامه، ممکن‌است به دلایل زیر باشد:
<br>
<br>
  * در تنظیمات لینوکس، باید منطقه‌ی زمانی سیستم را مطابق با مکان (کشور) موردنظر خودتان تنظیم نمایید؛ نه ایران و نه وقت‌جهانی
<br><br>
  * روش محاسبه نیز در ایران طبق الگوریتم مؤسسه ژئوفیزیک دانشگاه تهران است؛ امّا در مساجد اکثر کشورها طبق روش‌های اهل‌سنّت محاسبه می‌شود و می‌تواند چند دقیقه متفاوت باشد. البتّه روش اهل تشیّع (دانشگاه‌تهران و انجمن لواء قم) به‌دلیل رعایت احتیاط‌شدن بیشتر (مثلاً هنگام افطار)، برای روزه‌داری و انجام سایر تکالیف «توصیه» می‌گردد.
<br><br>
  * همچنین برای کشورهای خیلی‌نزدیک به قطب‌های زمین، که روزها یا شب‌های بسیار طولانی دارند، این افزونه دقیق نیست و با رؤیت آسمان، به تکالیف شرعی عمل نمایید.

</div>

**Comment by SCR-IR** [comment]
<div dir=rtl>
با در‌نظر‌گرفتن نکاتی که ذکر گردید؛ اگر همچنان مشکلی وجو داشت، کشور و شهر موردنظر و مختصات آن را ارسال فرمایید تا بررسی کنیم.
</div>

**Comment by khodayard** [comment]
بله این کارها رو کردم، مختصاتی که وارد کردم این هست:
50.35782, 7.83657
و زمان سیستم هم به درستی به آلمان تنظیم شده 
ولی اوقات شرعی اشتباه نشون داده می‌شن و زیرش هم با فونت قرمز نوشته شده «منطقه زمانی سیستم بررسی شود«. 
اگه لازم بود بفرمایید که عکس و ... بفرستم

ممنون

**Comment by SCR-IR** [comment]
![2021](https://user-images.githubusercontent.com/43960795/103440116-56efad80-4c43-11eb-93c3-c59aa7b83706.png)
طبق تنظیمات شما، خروجی بالا را خواهیم داشت. آیا اوقات اشتباه است؟

**Comment by khodayard** [comment]
بله دستتون درد نکنه. اشتباه از من بود که جای طول و عرض رو اشتباه وارد کرده بودم.
