### ISSUE TITLE
در بروز رسانی جدید ارور دریافت میکنم

### ISSUE THREAD

**Issue by miladsport** [SCR-IR/gnome-shamsi-calendar#6]
مارس 02 18:27:54 milad-MS-7B24 gnome-shell[3002]: JS ERROR: Extension shamsi-calendar@gnome.scr.ir: Error: A different version was loaded previously. You need to log out for changes to take effect.
مارس 02 18:27:54 milad-MS-7B24 gnome-shell[3002]: JS ERROR: Extension shamsi-calendar@gnome.scr.ir: Error: A different version was loaded previously. You need to log out for changes to take effect.
مارس 02 18:28:19 milad-MS-7B24 gnome-shell[3002]: JS ERROR: Extension shamsi-calendar@gnome.scr.ir: Error: A different version was loaded previously. You need to log out for changes to take effect.
مارس 02 18:30:27 milad-MS-7B24 gnome-shell[3002]: JS ERROR: Extension shamsi-calendar@gnome.scr.ir: Error: A different version was loaded previously. You need to log out for changes to take effect.
مارس 02 18:36:58 milad-MS-7B24 gnome-shell[3002]: JS ERROR: Extension shamsi-calendar@gnome.scr.ir: Error: A different version was loaded previously. You need to log out for changes to take effect.
مارس 02 18:45:30 milad-MS-7B24 gnome-shell[3002]: JS ERROR: Extension shamsi-calendar@gnome.scr.ir: Error: A different version was loaded previously. You need to log out for changes to take effect.
سیستم عامل لینوکس اوبونتو ۱۲.۰۴.۲

**Comment by SCR-IR** [comment]
<div dir="rtl">
احتمالاً با یکبار LogOut و Login کردن، این مشکل حل خواهد شد و افزونه اجرا می‌شود.

اگر از طریق افزونه‌ی مرورگر و سایت
[extensions.gnome.org](https://extensions.gnome.org)
اقدام می‌نمایید، معمولاً دکمه‌ی بروزرسانی، درست کار نمی‌کند و بهتر است حذف+نصب کنید.
<br>
ضمناً گویا نسخه‌ی اوبونتو (۱۲) اشتباه تایپ شده. الآن فقط نسخه‌های ۱۸ و ۲۰ رایج هستند.
<br>
اگر مشکل برطرف نشد، لطفاً دستورات زیر را در ترمینال اجرا نموده و خروجی را ارسال بفرمایید:
</div>

```
uname -v
```
```
gnome-shell --version
```
