### ISSUE TITLE
ایراد در زمان مانده تا عید

### ISSUE THREAD

**Issue by mimsadX** [SCR-IR/gnome-shamsi-calendar#7]
سلام
حدود 45 دقیقه مانده تا عید
* نشون می ده
![Screenshot from 2021-03-20 12-25-32](https://user-images.githubusercontent.com/70805659/111864681-b3778480-8977-11eb-84e9-4f0b18d889d7.png)

**Comment by SCR-IR** [comment]
<div dir=rtl>
سلام، این قابلیت که از نسخه‌ی قدیم در افزونه موجود است، فقط روزشمار بوده و ساعت‌شمار نیست.
امّا إن‌شاء‌الله تا قبل از نوروز ۱۴۰۱ تغییرات اساسی در امکانات اضافه انجام خواهد شد.
</div>
