### ISSUE TITLE
Installation error

### ISSUE THREAD

**Issue by mrvafa** [SCR-IR/gnome-shamsi-calendar#8]
Hi. thanks for this awesome application. today I got this error. I reinstalled it, but doesn't work.
Error: Requiring Gst, version none: Typelib file for namespace 'Gst' (any version) not found

Stack trace:
  @/home/mrvafa/.local/share/gnome-shell/extensions/shamsi-calendar@gnome.scr.ir/sound.js:3:7
  @/home/mrvafa/.local/share/gnome-shell/extensions/shamsi-calendar@gnome.scr.ir/prefs.js:16:7
  _getExtensionPrefsModule@resource:///org/gnome/shell/extensionPrefs/main.js:75:13
  wrapper@resource:///org/gnome/gjs/modules/_legacy.js:82:22
  _selectExtension@resource:///org/gnome/shell/extensionPrefs/main.js:90:31
  wrapper@resource:///org/gnome/gjs/modules/_legacy.js:82:22
  _onCommandLine@resource:///org/gnome/shell/extensionPrefs/main.js:243:17
  wrapper@resource:///org/gnome/gjs/modules/_legacy.js:82:22
  main@resource:///org/gnome/shell/extensionPrefs/main.js:397:5
  @<main>:1:43

**Comment by SCR-IR** [comment]
<div dir=rtl>
سلام، معمولاً کتابخانه‌ی مربوط به این خطا به‌همراه گنوم ۳.۲۸ و بالاتر به‌صورت پیشفرض یافت می‌شود.
<br><br>
لطفاً با پاسخ به چند پرسش، ما را در یافتن دلیل این مشکل یاری فرمایید:
<br>
۱- نام توزیع لینوکس شما و نسخه‌ی آن چیست؟
<br>
۲- آیا میز‌کار اصلی آن از ابتدا گنوم بوده یا اینکه بعداً گنوم را به آن اضافه (نصب) کرده‌اید؟
<br>
۳- آیا این احتمال وجود دارد که کتابخانه‌ی مربوطه را خودتان قبلاً حذف نموده‌باشید؟
<br><br>
بهتر است نصب بسته‌های زیر را امتحان کنید و سپس گنوم را ری‌استارت نمایید:
<br>
gir1.2-gst-plugins-base-1.0
<br>
یا
<br>
gst-plugins-base1.0 gst-plugins-good1.0 gst-plugins-ugly1.0 gst-plugins-bad1.0 gstreamer1.0
<br>
احتمالاً مشکل شما حل خواهد شد
<br>
</div>

```sudo apt install gir1.2-gst-plugins-base-1.0```

```sudo apt install gst-plugins-base1.0 gst-plugins-good1.0 gst-plugins-ugly1.0 gst-plugins-bad1.0 gstreamer1.0```

**Comment by mrvafa** [comment]
Thanks `sudo apt install gir1.2-gst-plugins-base-1.0` solves the issue.
