### ISSUE TITLE
Miss-placed window and white background on Ubuntu 20.04

### ISSUE THREAD

**Issue by Deihim007** [SCR-IR/gnome-shamsi-calendar#9]
![image](https://user-images.githubusercontent.com/22246989/117372492-dede1080-aede-11eb-8218-078c5e9fb580.png)

**Comment by mimsadAlef** [comment]
برای من هم این مشکل وجود دارد

**Comment by SCR-IR** [comment]
<div dir=rtl>
حاشیه‌ی سفیدرنگ درون تصویر، توسّط تم گنوم کنترل می‌شود؛ اما سعی می‌کنیم در آینده امکان تغییر رنگ پوسته را به افزونه اضافه کنیم
</div>
